export const typeColors: { [key: string]: string } = {
  normal: "bg-[#9FA19F] text-white",
  fire: "bg-[#E03A3A] text-white",
  water: "bg-[#1e90ff] text-white",
  electric: "bg-[#FAC000] text-white",
  grass: "bg-[#50C878] text-white",
  ice: "bg-[#3DCEF3] text-white",
  fighting: "bg-[#bf5858] text-white",
  poison: "bg-[#9141CB] text-white",
  ground: "bg-[#915121] text-white",
  flying: "bg-[#81B9EF] text-white",
  psychic: "bg-[#EF4179] text-white",
  bug: "bg-[#91A119] text-white",
  rock: "bg-[#AFA981] text-white",
  ghost: "bg-[#704170] text-white",
  dragon: "bg-[#882eff] text-white",
  dark: "bg-[#624D4E] text-white",
  steel: "bg-[#60A1B8] text-white",
  fairy: "bg-[#EF70EF] text-white",
};
